<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <!-- Benchmarks -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <!-- ClrProfiler.DatadogTracing -->
    <PackageVersion Include="DogStatsD-CSharp-Client" Version="9.2.1" />
    <PackageVersion Include="ZLogger" Version="2.5.10" />
    <!-- Tests -->
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="TUnit" Version="1.12.111" />
  </ItemGroup>
</Project>
