name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: dotnet build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: dotnet test
        run: dotnet test --no-build -c ${{ env.BUILD_CONFIG }} --logger GitHubActions
