name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: dotnet build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      - name: dotnet test
        run: dotnet test --no-build -c ${{ env.BUILD_CONFIG }} --logger GitHubActions
