name: Build (debug)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: dotnet build
        run: dotnet build -c ${{ env.BUILD_CONFIG }}
      # - name: dotnet test
      #   run: dotnet test -c ${{ env.BUILD_CONFIG }} --logger GitHubActions
