name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

env:
  BUILD_CONFIG: Release

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      # tag
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      # build
      - run: dotnet build -c ${{ env.BUILD_CONFIG }} -p:Version=${{ env.GIT_TAG }}
      # pack
      - run: dotnet pack -c ${{ env.BUILD_CONFIG }} -p:Version=${{ env.GIT_TAG }} -o ./.nuget/
      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ./.nuget/
          retention-days: 1
          if-no-files-found: error

  create-release:
    needs: [build-dotnet]
    runs-on: ubuntu-latest
    steps:
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      # nuget
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ./nuget
      - name: List Nuget
        run: ls -al ./nuget
      # release
      - name: Create Release
        run: gh release create ${{ env.GIT_TAG }} --draft --verify-tag --title "Ver.${{ env.GIT_TAG }}" --generate-notes
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # upload nuget
      - run: dotnet nuget push "./nuget/*.nupkg" --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.SYNCED_NUGET_KEY }}
